import VArea from './v-area.vue'
import VAxis from './v-axis.vue'
import VBar from './v-bar.vue'
import VChart from './v-chart.vue'
import VGuide from './v-guide.vue'
import VLegend from './v-legend.vue'
import VLine from './v-line.vue'
import VPie from './v-pie.vue'
import VPoint from './v-point.vue'
import VScale from './v-scale.vue'
import VTooltip from './v-tooltip.vue'
export { VArea, VAxis, VBar, VChart, VGuide, VLegend, VLine, VPie, VPoint, VScale, VTooltip }
