import Vue from 'vue'
import {
  Toast,
  Icon,
  PullRefresh,
  List,
  Search,
  Tab,
  Tabs,
  Swipe,
  SwipeItem,
  Uploader,
  Lazyload,
  Switch,
  DatetimePicker,
  Button,
  RadioGroup,
  Radio,
  Area,
  Popup,
  Picker,
  Progress,
  Loading,
  Dialog,
  Notify,
  Tag,
  TreeSelect,
  Checkbox,
  Tabbar,
  TabbarItem,
  Cell,
  CellGroup,
  CheckboxGroup,
  SubmitBar,
  Actionsheet,
  SwipeCell
} from 'vant'
Vue.use(Toast)
Vue.use(Icon)
Vue.use(PullRefresh)
Vue.use(List)
Vue.use(Search)
Vue.use(Tab).use(Tabs)
Vue.use(Swipe).use(SwipeItem)
Vue.use(Uploader)
Vue.use(Lazyload)
Vue.use(Switch)
Vue.use(DatetimePicker)
Vue.use(Button)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Area)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(Progress)
Vue.use(Loading)
Vue.use(Dialog)
Vue.use(Notify)
Vue.use(Tag)
Vue.use(TreeSelect)
Vue.use(Checkbox)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Cell).use(CellGroup)
Vue.use(CheckboxGroup)

Vue.use(SubmitBar)
Vue.use(Actionsheet)

Vue.use(SwipeCell)
